language: android

notifications:
  email: false

sudo: false

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

android:
  components:
    - platform-tools
    - tools
    - tools
    - build-tools-25.0.2
    - android-25
    - sys-img-armeabi-v7a-addon-google_apis-google-21
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25

env:
   matrix:
      - ANDROID_TARGET=android-15
      - ANDROID_TARGET=android-16
      - ANDROID_TARGET=android-17
      - ANDROID_TARGET=android-18
      - ANDROID_TARGET=android-19
      - ANDROID_TARGET=android-21
      - ANDROID_TARGET=android-24

before_script:
    - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi armeabi-v7a --skin WVGA800
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - ./gradlew build